CREATE TABLE EMPDB(
idx NUMBER PRIMARY KEY,
NAME VARCHAR2(15) NOT NULL,
BIRTH DATE ,
PHONE VARCHAR2(30),
ADDR VARCHAR2(30),
EMAIL VARCHAR2(30)
);

CREATE SEQUENCE emp_idx increment by 1 start with 1 nocycle nocache;

ALTER TABLE EMPDB ADD CONSTRAINT UNIQUE_P UNIQUE(PHONE);

DROP TABLE EMPDB;

SELECT * FROM EMPDB;

SELECT * FROM EMPDB WHERE IDX=11;

UPDATE EMPDB SET NAME='김민성', BIRTH='1995-12-12', PHONE='010-4569-2804', ADDR='양산시 물금읍', EMAIL='cmg1411@naver.com' WHERE IDX=3;

SELECT EMP_IDX.CURRVAL FROM DUAL;